#!/usr/bin/env ansible-playbook
---

- hosts: localhost

  vars:
    # base package on GNU/Linux.
    base_packages:
      - bash
      - bash-completion
      - ca-certificates
      - curl
      - git
      - openssl
      - sshpass

    # Alpine Linux.
    apk_packages:
      - openssh-client
      - vim

    # Debian, Ubuntu.
    apt_packages: "{{ apk_packages }}"

    ssh_private_key_url: "https://raw.githubusercontent.com/jianhuashao/alicloud_test/master/env/id_rsa"
   
  tasks:

    # General Linux.
    - name: install same packages
      package: name={{ item }} state=present
      with_items: "{{ base_packages }}"
      when:
        - base_packages is defined
        - ansible_pkg_mgr != "portage"

    # Debian, Ubuntu.
    - name: install apt packages
      apt: name={{ item }} state=present
      with_items: "{{ apt_packages }}"
      when:
        - apt_packages is defined
        - ansible_pkg_mgr == "apt"

    # Create `ssh_config` directory.
    - name: create `/root/.ssh` directory
      file: path=/root/.ssh state=directory mode=0700

    # Get the ssh private key.
    - name: get the ssh private key
      get_url: >
        url={{ ssh_private_key_url }} dest=/root/.ssh/id_rsa mode=0600
        checksum=md5:6cc26e77bf23a9d72a51b22387bea61f
