#!/usr/bin/env ansible-playbook
---

- hosts: localhost

  vars:
    # Python depedency to use docker via ansible
    pip_packages:
      - docker-py
      - docker-compose

    dockerfile_url: "https://raw.githubusercontent.com/crccheck/docker-hello-world/master/Dockerfile"
    html_url: "https://raw.githubusercontent.com/crccheck/docker-hello-world/master/index.html"

  tasks: # setup docker web server

    # this is only a simple to install docker
    # TODO: configure docker in a formal way
    - name: install docker via apt 
      apt: name=docker.io state=present

    # General Python packages.
    - name: install some pip packages
      pip: name={{ item }} state=present
      with_items: "{{ pip_packages }}"
      when: pip_packages is defined

    - name: create project folder
      shell: mkdir -p /root/app_web_docker/

    - name: get docker file
      get_url: url={{ dockerfile_url }} dest=/root/app_web_docker/ mode=0644

    - name: get html file
      get_url: url={{ html_url }} dest=/root/app_web_docker/ mode=0644

    - name: build the image
      shell: cd /root/app_web_docker/; docker build . -t web_docker

    - name: run the site in a docker container
      shell: cd /root/app_web_docker/; docker run -d --name web_docker -p 32768:8000 web_docker
    
  